name = "furban-backend"
main = "src/index.ts"
compatibility_date = "2024-12-04"

# Custom domain route
routes = [
  { pattern = "api.furban.my.id", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "furban-db"
database_id = "4c6f79ab-9bf5-4f59-a823-ab66c7c3601b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "furban-media"

[vars]
JWT_SECRET = "dev-secret-key-change-in-prod"
FRONTEND_URL = "https://furban.my.id"
